# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b88103f00c4eee23828a5a825a91d7f4ff247bb90273afe6ccca0febfaee131be80370982dbc87338d2ead3fb6a86a567733c6beef92a87f0a02526b1294fadd
  instagram_id: ***REMOVED***
  instagram_secret: ***REMOVED***
  access_token_no1: 46569725.5106fe6.9d58de87453144cb8a4fe8af6d96a92e
  liked_instagram_shortcode: ***REMOVED***
  not_liked_instagram_shortcode: ***REMOVED***

test:
  secret_key_base: 956b20629e6e3a78cabd9553607a457b8e39b6da79d2039a1c24d57086eaa1e1ac237dfcf5901fd7f2e89c09d9153f7af9c4d6b3c90488063cf680f3ea0049a1
  instagram_id: ***REMOVED***
  instagram_secret: ***REMOVED***
  access_token_no1: 46569725.5106fe6.9d58de87453144cb8a4fe8af6d96a92e
  liked_instagram_shortcode: ***REMOVED***
  not_liked_instagram_shortcode: ***REMOVED***

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
